# Logging filters
# loguru:
#     '': INFO
#     urllib3: WARNING
#     asyncio: WARNING
#     aiohttp: WARNING
#     runner.manager: WARNING
  
# Bind address and port
http:
    host: '0.0.0.0'
    port: 8050

webui:
    enabled: False
    static_path: 'webui/dist'

database:
    # dsn: 'postgres://postgres:password@database/push_store'
    dsn: 'postgres://postgres:password@127.0.0.1/push_store'
