version: '2.4'

networks:
  push_store:
    driver: bridge

volumes:
  grafana-storage: {}
  database-storage: {}

services:
  database:
    build:
      context: ./docker/timescaledb
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - database-storage:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    networks:
      - push_store
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    ports: 
      - 3000:3000
    networks:
      - push_store
    depends_on:
      database:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: ["./entrypoint.sh"]
    ports: 
      - 8050:8050
    volumes:
      - .:/code
    links:
      - database
    networks:
      - push_store
    depends_on:
      database:
        condition: service_healthy