version: '3.6'

networks:
  push_store:
    driver: bridge

services:
  database:
    build:
      context: ./docker/timescaledb
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/timescaledb:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    networks:
      - push_store

  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    ports: 
      - 3000:3000
    networks:
      - push_store

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ["python",  "-m", "server"]
    ports: 
      - 8050:8050
    volumes:
      - .:/code
    links:
      - database
    depends_on:
      - database
    networks:
      - push_store