apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    orgId: 1
    url: database
    password: "password"
    user: postgres
    database: push_store
    basicAuth: false
    isDefault: true
    jsonData:
        postgresVersion: 1000
        sslmode: disable
        timescaledb: true
    editable: false